"""
Code taken from: https://github.com/zhengqili/MegaDepth modified
"""

import os
import sys
from functools import reduce

import torch
import torch.nn as nn
from torch.autograd import Variable
from torch.nn.parallel import DistributedDataParallel, DataParallel

from geopose.model.new_model import NormieNet


class HourglassModel:
    @staticmethod
    def name():
        return 'HourglassModel'

    def __init__(self, weights_path=None):
        # self.Tensor = torch.cuda.FloatTensor if self.gpu_ids else torch.Tensor
        # self.model = NormieNet()
        self.model = hourglass_refactored

        # must use DataParallel to load weights saved with this setting
        self.model = torch.nn.parallel.DataParallel(self.model, device_ids=[0])

        if weights_path is not None:
            if weights_path == 'generalization':
                weights_path = 'geopose/checkpoints/best_generalization_net_G.pth'

            self.model.load_state_dict(torch.load(weights_path))

        else:
            # training from scratch
            pass

        self.model.cuda()

    def switch_to_train(self):
        self.model.train()

    def switch_to_eval(self):
        self.model.eval()


class LambdaBase(nn.Sequential):
    def __init__(self, fn, *args):
        super(LambdaBase, self).__init__(*args)
        self.lambda_func = fn

    def forward_prepare(self, input_):
        output = []
        for module in self._modules.values():
            output.append(module(input_))
        return output if output else input_


class Lambda(LambdaBase):
    def forward(self, input_):
        return self.lambda_func(self.forward_prepare(input_))


class Map(LambdaBase):
    def forward(self, input_):
        return list(map(self.lambda_func, self.forward_prepare(input_)))


class Reduce(LambdaBase):
    def forward(self, input_):
        return reduce(self.lambda_func, self.forward_prepare(input_))


"""
# todo fov
class FOV(nn.Module):
    def __init__(self, channels_in):
        super(FOV, self).__init__()
        pass

    def forward(self, x):
        # přičíst embedding fov ke vstupu
        pass
        
"""


def bn(c, affine=False):
    return nn.BatchNorm2d(c, 1e-05, 0.1, affine)


def conv11(c_in, c_out):
    return nn.Conv2d(c_in, c_out, (11, 11), (1, 1), (5, 5)), bn(c_out), nn.ReLU()


def conv7(c_in, c_out, bn_affine=False):
    return nn.Conv2d(c_in, c_out, (7, 7), (1, 1), (3, 3)), bn(c_out, bn_affine), nn.ReLU()


def conv5(c_in, c_out):
    return nn.Conv2d(c_in, c_out, (5, 5), (1, 1), (2, 2)), bn(c_out), nn.ReLU()


def conv3(c_in, c_out):
    return nn.Conv2d(c_in, c_out, (3, 3), (1, 1), (1, 1)), bn(c_out), nn.ReLU()


def conv1(c_in, c_out):
    return nn.Conv2d(c_in, c_out, (1, 1)), bn(c_out), nn.ReLU()


# @formatter:off
# noinspection DuplicatedCode
hourglass_refactored = nn.Sequential(
    *conv7(3, 128, bn_affine=True), nn.Sequential(
        Map(lambda x: x,  # ConcatTable,
            nn.Sequential(
                nn.MaxPool2d((2, 2), (2, 2)),
                Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                       nn.Sequential(*conv1(128, 32)),
                       nn.Sequential(*conv1(128, 32), *conv3(32, 32)),
                       nn.Sequential(*conv1(128, 32), *conv5(32, 32)),
                       nn.Sequential(*conv1(128, 32), *conv7(32, 32))),
                Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                       nn.Sequential(*conv1(128, 32)),
                       nn.Sequential(*conv1(128, 32), *conv3(32, 32)),
                       nn.Sequential(*conv1(128, 32), *conv5(32, 32)),
                       nn.Sequential(*conv1(128, 32), *conv7(32, 32))),
                nn.Sequential(Map(lambda x: x,  # ConcatTable,
                                  nn.Sequential(
                                      nn.MaxPool2d((2, 2), (2, 2)),
                                      Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                             nn.Sequential(*conv1(128, 32)),
                                             nn.Sequential(*conv1(128, 32), *conv3(32, 32)),
                                             nn.Sequential(*conv1(128, 32), *conv5(32, 32)),
                                             nn.Sequential(*conv1(128, 32), *conv7(32, 32))),
                                      Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                             nn.Sequential(*conv1(128, 64)),
                                             nn.Sequential(*conv1(128, 32), *conv3(32, 64)),
                                             nn.Sequential(*conv1(128, 32), *conv5(32, 64)),
                                             nn.Sequential(*conv1(128, 32), *conv7(32, 64))),
                                      nn.Sequential(Map(lambda x: x,  # ConcatTable,
                                                        nn.Sequential(
                                                            Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),
                                                                   # Concat,
                                                                   nn.Sequential(*conv1(256, 64)),
                                                                   nn.Sequential(*conv1(256, 32), *conv3(32, 64)),
                                                                   nn.Sequential(*conv1(256, 32), *conv5(32, 64)),
                                                                   nn.Sequential(*conv1(256, 32), *conv7(32, 64))),
                                                            Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),
                                                                   # Concat,
                                                                   nn.Sequential(*conv1(256, 64)),
                                                                   nn.Sequential(*conv1(256, 64), *conv3(64, 64)),
                                                                   nn.Sequential(*conv1(256, 64), *conv7(64, 64)),
                                                                   nn.Sequential(*conv1(256, 64), *conv11(64, 64)))),
                                                        nn.Sequential(
                                                            nn.AvgPool2d((2, 2), (2, 2)),
                                                            Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),
                                                                   # Concat,
                                                                   nn.Sequential(*conv1(256, 64)),
                                                                   nn.Sequential(*conv1(256, 32), *conv3(32, 64)),
                                                                   nn.Sequential(*conv1(256, 32), *conv5(32, 64)),
                                                                   nn.Sequential(*conv1(256, 32), *conv7(32, 64))),
                                                            Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),
                                                                   # Concat,
                                                                   nn.Sequential(*conv1(256, 64)),
                                                                   nn.Sequential(*conv1(256, 32), *conv3(32, 64)),
                                                                   nn.Sequential(*conv1(256, 32), *conv5(32, 64)),
                                                                   nn.Sequential(*conv1(256, 32), *conv7(32, 64))),
                                                            nn.Sequential(
                                                                Map(lambda x: x,  # ConcatTable,
                                                                    nn.Sequential(
                                                                        Reduce(
                                                                            lambda x, y, dim=1: torch.cat((x, y), dim),
                                                                            # Concat,
                                                                            nn.Sequential(
                                                                                *conv1(256, 64)),
                                                                            nn.Sequential(
                                                                                *conv1(256, 32), *conv3(32, 64)),
                                                                            nn.Sequential(
                                                                                *conv1(256, 32), *conv5(32, 64)),
                                                                            nn.Sequential(
                                                                                *conv1(256, 32), *conv7(32, 64))),
                                                                        Reduce(
                                                                            lambda x, y, dim=1: torch.cat((x, y), dim),
                                                                            # Concat,
                                                                            nn.Sequential(
                                                                                *conv1(256, 64)),
                                                                            nn.Sequential(
                                                                                *conv1(256, 32), *conv3(32, 64)),
                                                                            nn.Sequential(
                                                                                *conv1(256, 32), *conv5(32, 64)),
                                                                            nn.Sequential(
                                                                                *conv1(256, 32), *conv7(32, 64)))),
                                                                    nn.Sequential(
                                                                        nn.AvgPool2d((2, 2), (2, 2)),
                                                                        Reduce(
                                                                            lambda x, y, dim=1: torch.cat((x, y), dim),
                                                                            # Concat,
                                                                            nn.Sequential(
                                                                                *conv1(256, 64)),
                                                                            nn.Sequential(
                                                                                *conv1(256, 32), *conv3(32, 64)),
                                                                            nn.Sequential(
                                                                                *conv1(256, 32), *conv5(32, 64)),
                                                                            nn.Sequential(
                                                                                *conv1(256, 32), *conv7(32, 64))),
                                                                        Reduce(
                                                                            lambda x, y, dim=1: torch.cat((x, y), dim),
                                                                            # Concat,
                                                                            nn.Sequential(
                                                                                *conv1(256, 64)),
                                                                            nn.Sequential(
                                                                                *conv1(256, 32), *conv3(32, 64)),
                                                                            nn.Sequential(
                                                                                *conv1(256, 32), *conv5(32, 64)),
                                                                            nn.Sequential(
                                                                                *conv1(256, 32), *conv7(32, 64))),
                                                                        Reduce(
                                                                            lambda x, y, dim=1: torch.cat((x, y), dim),
                                                                            # Concat,
                                                                            nn.Sequential(
                                                                                *conv1(256, 64)),
                                                                            nn.Sequential(
                                                                                *conv1(256, 32), *conv3(32, 64)),
                                                                            nn.Sequential(
                                                                                *conv1(256, 32), *conv5(32, 64)),
                                                                            nn.Sequential(
                                                                                *conv1(256, 32), *conv7(32, 64))),
                                                                        nn.UpsamplingNearest2d(
                                                                            scale_factor=2), ), ),
                                                                Reduce(lambda x, y: x + y),  # CAddTable,
                                                            ), Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),
                                                                      # Concat,
                                                                      nn.Sequential(*conv1(256, 64)),
                                                                      nn.Sequential(*conv1(256, 32), *conv3(32, 64)),
                                                                      nn.Sequential(*conv1(256, 32), *conv5(32, 64)),
                                                                      nn.Sequential(*conv1(256, 32), *conv7(32, 64))),
                                                            Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),
                                                                   # Concat,
                                                                   nn.Sequential(*conv1(256, 64)),
                                                                   nn.Sequential(*conv1(256, 64), *conv3(64, 64)),
                                                                   nn.Sequential(*conv1(256, 64), *conv7(64, 64)),
                                                                   nn.Sequential(*conv1(256, 64), *conv11(64, 64))),
                                                            nn.UpsamplingNearest2d(scale_factor=2))),
                                                    Reduce(lambda x, y: x + y),  # CAddTable,
                                                    ),
                                      Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                             nn.Sequential(*conv1(256, 64)),
                                             nn.Sequential(*conv1(256, 32), *conv3(32, 64)),
                                             nn.Sequential(*conv1(256, 32), *conv5(32, 64)),
                                             nn.Sequential(*conv1(256, 32), *conv7(32, 64))),
                                      Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                             nn.Sequential(*conv1(256, 32)),
                                             nn.Sequential(*conv1(256, 32), *conv3(32, 32)),
                                             nn.Sequential(*conv1(256, 32), *conv5(32, 32)),
                                             nn.Sequential(*conv1(256, 32), *conv7(32, 32))),
                                      nn.UpsamplingNearest2d(scale_factor=2)),
                                  nn.Sequential(
                                      Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                             nn.Sequential(*conv1(128, 32)),
                                             nn.Sequential(*conv1(128, 32), *conv3(32, 32)),
                                             nn.Sequential(*conv1(128, 32), *conv5(32, 32)),
                                             nn.Sequential(*conv1(128, 32), *conv7(32, 32))),
                                      Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                             nn.Sequential(*conv1(128, 32)),
                                             nn.Sequential(*conv1(128, 64), *conv3(64, 32)),
                                             nn.Sequential(*conv1(128, 64), *conv7(64, 32)),
                                             nn.Sequential(*conv1(128, 64), *conv11(64, 32))))),
                              Reduce(lambda x, y: x + y),  # CAddTable,
                              ),
                Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                       nn.Sequential(*conv1(128, 32)),
                       nn.Sequential(*conv1(128, 64), *conv3(64, 32)),
                       nn.Sequential(*conv1(128, 64), *conv5(64, 32)),
                       nn.Sequential(*conv1(128, 64), *conv7(64, 32))),
                Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                       nn.Sequential(*conv1(128, 16)),
                       nn.Sequential(*conv1(128, 32), *conv3(32, 16)),
                       nn.Sequential(*conv1(128, 32), *conv7(32, 16)),
                       nn.Sequential(*conv1(128, 32), *conv11(32, 16))),
                nn.UpsamplingNearest2d(scale_factor=2)),
            nn.Sequential(
                Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                       nn.Sequential(*conv1(128, 16)),
                       nn.Sequential(*conv1(128, 64), *conv3(64, 16)),
                       nn.Sequential(*conv1(128, 64), *conv7(64, 16)),
                       nn.Sequential(*conv1(128, 64), *conv11(64, 16))))),
        Reduce(lambda x, y: x + y),
        # CAddTable,
    ), nn.Conv2d(64, 1, (3, 3), (1, 1), (1, 1)))


# noinspection DuplicatedCode
hg_model = nn.Sequential(  # Sequential,
    nn.Conv2d(3, 128, (7, 7), (1, 1), (3, 3)),
    nn.BatchNorm2d(128),
    nn.ReLU(),
    nn.Sequential(  # Sequential,
        Map(lambda x: x,  # ConcatTable,
            nn.Sequential(  # Sequential,
                      nn.MaxPool2d((2, 2), (2, 2)),
                      Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                             nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 32, (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                             nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 32, (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(32, 32, (3, 3), (1, 1), (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                             nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 32, (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(32, 32, (5, 5), (1, 1), (2, 2)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                             nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 32, (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(32, 32, (7, 7), (1, 1), (3, 3)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                             ),
                      Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                             nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 32, (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                             nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 32, (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(32, 32, (3, 3), (1, 1), (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                             nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 32, (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(32, 32, (5, 5), (1, 1), (2, 2)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                             nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 32, (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(32, 32, (7, 7), (1, 1), (3, 3)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                             ),
                      nn.Sequential(  # Sequential,
                          Map(lambda x: x,  # ConcatTable,
                              nn.Sequential(  # Sequential,
                                        nn.MaxPool2d((2, 2), (2, 2)),
                                        Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                               nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                               nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 32, (3, 3), (1, 1), (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                               nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 32, (5, 5), (1, 1), (2, 2)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                               nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 32, (7, 7), (1, 1), (3, 3)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                               ),
                                        Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                               nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 64, (1, 1)),
                                                         nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                               nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 64, (3, 3), (1, 1), (1, 1)),
                                                         nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                               nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 64, (5, 5), (1, 1), (2, 2)),
                                                         nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                               nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 64, (7, 7), (1, 1), (3, 3)),
                                                         nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                               ),
                                        nn.Sequential(  # Sequential,
                                            Map(lambda x: x,  # ConcatTable,
                                                nn.Sequential(  # Sequential,
                                                          Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),
                                                                 # Concat,
                                                                 nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 64, (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                 nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 32, (1, 1)),
                                                                           nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(32, 64, (3, 3), (1, 1), (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                 nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 32, (1, 1)),
                                                                           nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(32, 64, (5, 5), (1, 1), (2, 2)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                 nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 32, (1, 1)),
                                                                           nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(32, 64, (7, 7), (1, 1), (3, 3)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                 ),
                                                          Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),
                                                                 # Concat,
                                                                 nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 64, (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                 nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 64, (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(64, 64, (3, 3), (1, 1), (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                 nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 64, (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(64, 64, (7, 7), (1, 1), (3, 3)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                 nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 64, (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(64, 64, (11, 11), (1, 1), (5, 5)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                 ),
                                                      ),
                                                nn.Sequential(  # Sequential,
                                                          nn.AvgPool2d((2, 2), (2, 2)),
                                                          Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),
                                                                 # Concat,
                                                                 nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 64, (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                 nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 32, (1, 1)),
                                                                           nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(32, 64, (3, 3), (1, 1), (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                 nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 32, (1, 1)),
                                                                           nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(32, 64, (5, 5), (1, 1), (2, 2)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                 nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 32, (1, 1)),
                                                                           nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(32, 64, (7, 7), (1, 1), (3, 3)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                 ),
                                                          Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),
                                                                 # Concat,
                                                                 nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 64, (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                 nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 32, (1, 1)),
                                                                           nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(32, 64, (3, 3), (1, 1), (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                 nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 32, (1, 1)),
                                                                           nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(32, 64, (5, 5), (1, 1), (2, 2)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                 nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 32, (1, 1)),
                                                                           nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(32, 64, (7, 7), (1, 1), (3, 3)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                 ),
                                                          nn.Sequential(  # Sequential,
                                                              Map(lambda x: x,  # ConcatTable,
                                                                  nn.Sequential(  # Sequential,
                                                                            Reduce(
                                                                                lambda x, y, dim=1: torch.cat((x, y),
                                                                                                              dim),
                                                                                # Concat,
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 64, (1, 1)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (3, 3), (1, 1),
                                                                                              (1, 1)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (5, 5), (1, 1),
                                                                                              (2, 2)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (7, 7), (1, 1),
                                                                                              (3, 3)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                            ),
                                                                            Reduce(
                                                                                lambda x, y, dim=1: torch.cat((x, y),
                                                                                                              dim),
                                                                                # Concat,
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 64, (1, 1)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (3, 3), (1, 1),
                                                                                              (1, 1)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (5, 5), (1, 1),
                                                                                              (2, 2)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (7, 7), (1, 1),
                                                                                              (3, 3)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                            ),
                                                                        ),
                                                                  nn.Sequential(  # Sequential,
                                                                            nn.AvgPool2d((2, 2), (2, 2)),
                                                                            Reduce(
                                                                                lambda x, y, dim=1: torch.cat((x, y),
                                                                                                              dim),
                                                                                # Concat,
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 64, (1, 1)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (3, 3), (1, 1),
                                                                                              (1, 1)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (5, 5), (1, 1),
                                                                                              (2, 2)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (7, 7), (1, 1),
                                                                                              (3, 3)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                            ),
                                                                            Reduce(
                                                                                lambda x, y, dim=1: torch.cat((x, y),
                                                                                                              dim),
                                                                                # Concat,
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 64, (1, 1)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (3, 3), (1, 1),
                                                                                              (1, 1)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (5, 5), (1, 1),
                                                                                              (2, 2)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (7, 7), (1, 1),
                                                                                              (3, 3)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                            ),
                                                                            Reduce(
                                                                                lambda x, y, dim=1: torch.cat((x, y),
                                                                                                              dim),
                                                                                # Concat,
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 64, (1, 1)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (3, 3), (1, 1),
                                                                                              (1, 1)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (5, 5), (1, 1),
                                                                                              (2, 2)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (7, 7), (1, 1),
                                                                                              (3, 3)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                            ),
                                                                            nn.UpsamplingNearest2d(scale_factor=2),
                                                                        ),
                                                                  ),
                                                              Reduce(lambda x, y: x + y),  # CAddTable,
                                                          ),
                                                          Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),
                                                                 # Concat,
                                                                 nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 64, (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                 nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 32, (1, 1)),
                                                                           nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(32, 64, (3, 3), (1, 1), (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                 nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 32, (1, 1)),
                                                                           nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(32, 64, (5, 5), (1, 1), (2, 2)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                 nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 32, (1, 1)),
                                                                           nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(32, 64, (7, 7), (1, 1), (3, 3)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                 ),
                                                          Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),
                                                                 # Concat,
                                                                 nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 64, (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                 nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 64, (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(64, 64, (3, 3), (1, 1), (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                 nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 64, (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(64, 64, (7, 7), (1, 1), (3, 3)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                 nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 64, (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(64, 64, (11, 11), (1, 1), (5, 5)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                 ),
                                                          nn.UpsamplingNearest2d(scale_factor=2),
                                                      ),
                                                ),
                                            Reduce(lambda x, y: x + y),  # CAddTable,
                                        ),
                                        Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                               nn.Sequential(  # Sequential,
                                                         nn.Conv2d(256, 64, (1, 1)),
                                                         nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                               nn.Sequential(  # Sequential,
                                                         nn.Conv2d(256, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 64, (3, 3), (1, 1), (1, 1)),
                                                         nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                               nn.Sequential(  # Sequential,
                                                         nn.Conv2d(256, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 64, (5, 5), (1, 1), (2, 2)),
                                                         nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                               nn.Sequential(  # Sequential,
                                                         nn.Conv2d(256, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 64, (7, 7), (1, 1), (3, 3)),
                                                         nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                               ),
                                        Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                               nn.Sequential(  # Sequential,
                                                         nn.Conv2d(256, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                               nn.Sequential(  # Sequential,
                                                         nn.Conv2d(256, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 32, (3, 3), (1, 1), (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                               nn.Sequential(  # Sequential,
                                                         nn.Conv2d(256, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 32, (5, 5), (1, 1), (2, 2)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                               nn.Sequential(  # Sequential,
                                                         nn.Conv2d(256, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 32, (7, 7), (1, 1), (3, 3)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                               ),
                                        nn.UpsamplingNearest2d(scale_factor=2),
                                    ),
                              nn.Sequential(  # Sequential,
                                        Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                               nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                               nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 32, (3, 3), (1, 1), (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                               nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 32, (5, 5), (1, 1), (2, 2)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                               nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 32, (7, 7), (1, 1), (3, 3)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                               ),
                                        Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                               nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                               nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 64, (1, 1)),
                                                         nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(64, 32, (3, 3), (1, 1), (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                               nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 64, (1, 1)),
                                                         nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(64, 32, (7, 7), (1, 1), (3, 3)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                               nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 64, (1, 1)),
                                                         nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(64, 32, (11, 11), (1, 1), (5, 5)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                               ),
                                    ),
                              ),
                          Reduce(lambda x, y: x + y),  # CAddTable,
                      ),
                      Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                             nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 32, (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                             nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 64, (1, 1)),
                                       nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(64, 32, (3, 3), (1, 1), (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                             nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 64, (1, 1)),
                                       nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(64, 32, (5, 5), (1, 1), (2, 2)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                             nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 64, (1, 1)),
                                       nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(64, 32, (7, 7), (1, 1), (3, 3)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                             ),
                      Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                             nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 16, (1, 1)),
                                       nn.BatchNorm2d(16, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                             nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 32, (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(32, 16, (3, 3), (1, 1), (1, 1)),
                                       nn.BatchNorm2d(16, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                             nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 32, (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(32, 16, (7, 7), (1, 1), (3, 3)),
                                       nn.BatchNorm2d(16, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                             nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 32, (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(32, 16, (11, 11), (1, 1), (5, 5)),
                                       nn.BatchNorm2d(16, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                             ),
                      nn.UpsamplingNearest2d(scale_factor=2),
                  ),
            nn.Sequential(  # Sequential,
                      Reduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                             nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 16, (1, 1)),
                                       nn.BatchNorm2d(16, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                             nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 64, (1, 1)),
                                       nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(64, 16, (3, 3), (1, 1), (1, 1)),
                                       nn.BatchNorm2d(16, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                             nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 64, (1, 1)),
                                       nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(64, 16, (7, 7), (1, 1), (3, 3)),
                                       nn.BatchNorm2d(16, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                             nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 64, (1, 1)),
                                       nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(64, 16, (11, 11), (1, 1), (5, 5)),
                                       nn.BatchNorm2d(16, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                             ),
                  ),
            ),
        Reduce(lambda x, y: x + y),  # CAddTable,
    ),
    nn.Conv2d(64, 1, (3, 3), (1, 1), (1, 1)),
)
