"""
Code taken from: https://github.com/zhengqili/MegaDepth modified
"""

import os
import sys
from functools import reduce

import torch
import torch.nn as nn
from torch.autograd import Variable
from torch.nn.parallel import DistributedDataParallel, DataParallel


class HourglassModel:
    @staticmethod
    def name():
        return 'HourglassModel'

    def __init__(self, opt, weights_path=None):
        self.opt = opt
        self.gpu_ids = opt.gpu_ids
        self.isTrain = opt.isTrain
        # self.Tensor = torch.cuda.FloatTensor if self.gpu_ids else torch.Tensor
        self.save_dir = os.path.join(opt.checkpoints_dir, opt.name)

        print("============= LOADING Hourglass NETWORK =============")
        self.model = hg_model

        # must use DataParallel to load weights saved with this setting
        self.model = torch.nn.parallel.DataParallel(self.model, device_ids=[0])

        if weights_path is None:
            self.load_network('G', 'best_generalization')

            # self.load_network('G', 'saved')
            # self.load_network('G', 'saved_1480.2093')
            # self.load_network('G', 'saved_1457.3193')
            # self.load_network('G', 'saved_1436.4768')
            # self.load_network('G', 'saved_600batches_no-logs_lr2_by_100')
            # self.load_network('G', 'saved_1.1111')
        else:
            self.model.load_state_dict(torch.load(weights_path))

        self.model.cuda()

    def save_network(self, network_label, epoch_label):
        save_filename = '_%s_net_%s.pth' % (epoch_label, network_label)
        save_path = os.path.join(self.save_dir, save_filename)
        torch.save(self.model.cpu().state_dict(), save_path)
        if len(self.gpu_ids) and torch.cuda.is_available():
            self.model.cuda()

    def load_network(self, network_label, epoch_label):
        save_filename = '%s_net_%s.pth' % (epoch_label, network_label)
        save_path = self.save_dir + os.sep + save_filename
        print('Loading model weights from:', save_path)
        if not os.path.isfile(save_path):
            save_path = os.path.join('geopose', 'checkpoints', save_path)
            if not os.path.isfile(save_path):
                print('base_model: load_network: Weights not loaded :C\ncould not find file:', save_path,
                      file=sys.stderr)

        self.model.load_state_dict(torch.load(save_path))

    def switch_to_train(self):
        self.model.train()

    def switch_to_eval(self):
        self.model.eval()

class LambdaBase(nn.Sequential):
    def __init__(self, fn, *args):
        super(LambdaBase, self).__init__(*args)
        self.lambda_func = fn

    def forward_prepare(self, input_):
        output = []
        for module in self._modules.values():
            output.append(module(input_))
        return output if output else input_


class Lambda(LambdaBase):
    def forward(self, input_):
        return self.lambda_func(self.forward_prepare(input_))


class LambdaMap(LambdaBase):
    def forward(self, input_):
        return list(map(self.lambda_func, self.forward_prepare(input_)))


class LambdaReduce(LambdaBase):
    def forward(self, input_):
        return reduce(self.lambda_func, self.forward_prepare(input_))


# noinspection DuplicatedCode
hg_model = nn.Sequential(  # Sequential,
    nn.Conv2d(3, 128, (7, 7), (1, 1), (3, 3)),
    nn.BatchNorm2d(128),
    nn.ReLU(),
    nn.Sequential(  # Sequential,
        LambdaMap(lambda x: x,  # ConcatTable,
                  nn.Sequential(  # Sequential,
                      nn.MaxPool2d((2, 2), (2, 2)),
                      LambdaReduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                   nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 32, (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                                   nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 32, (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(32, 32, (3, 3), (1, 1), (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                                   nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 32, (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(32, 32, (5, 5), (1, 1), (2, 2)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                                   nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 32, (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(32, 32, (7, 7), (1, 1), (3, 3)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                                   ),
                      LambdaReduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                   nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 32, (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                                   nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 32, (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(32, 32, (3, 3), (1, 1), (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                                   nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 32, (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(32, 32, (5, 5), (1, 1), (2, 2)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                                   nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 32, (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(32, 32, (7, 7), (1, 1), (3, 3)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                                   ),
                      nn.Sequential(  # Sequential,
                          LambdaMap(lambda x: x,  # ConcatTable,
                                    nn.Sequential(  # Sequential,
                                        nn.MaxPool2d((2, 2), (2, 2)),
                                        LambdaReduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                                     nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                                     nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 32, (3, 3), (1, 1), (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                                     nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 32, (5, 5), (1, 1), (2, 2)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                                     nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 32, (7, 7), (1, 1), (3, 3)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                                     ),
                                        LambdaReduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                                     nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 64, (1, 1)),
                                                         nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                                     nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 64, (3, 3), (1, 1), (1, 1)),
                                                         nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                                     nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 64, (5, 5), (1, 1), (2, 2)),
                                                         nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                                     nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 64, (7, 7), (1, 1), (3, 3)),
                                                         nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                                     ),
                                        nn.Sequential(  # Sequential,
                                            LambdaMap(lambda x: x,  # ConcatTable,
                                                      nn.Sequential(  # Sequential,
                                                          LambdaReduce(lambda x, y, dim=1: torch.cat((x, y), dim),
                                                                       # Concat,
                                                                       nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 64, (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                       nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 32, (1, 1)),
                                                                           nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(32, 64, (3, 3), (1, 1), (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                       nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 32, (1, 1)),
                                                                           nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(32, 64, (5, 5), (1, 1), (2, 2)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                       nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 32, (1, 1)),
                                                                           nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(32, 64, (7, 7), (1, 1), (3, 3)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                       ),
                                                          LambdaReduce(lambda x, y, dim=1: torch.cat((x, y), dim),
                                                                       # Concat,
                                                                       nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 64, (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                       nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 64, (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(64, 64, (3, 3), (1, 1), (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                       nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 64, (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(64, 64, (7, 7), (1, 1), (3, 3)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                       nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 64, (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(64, 64, (11, 11), (1, 1), (5, 5)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                       ),
                                                      ),
                                                      nn.Sequential(  # Sequential,
                                                          nn.AvgPool2d((2, 2), (2, 2)),
                                                          LambdaReduce(lambda x, y, dim=1: torch.cat((x, y), dim),
                                                                       # Concat,
                                                                       nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 64, (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                       nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 32, (1, 1)),
                                                                           nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(32, 64, (3, 3), (1, 1), (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                       nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 32, (1, 1)),
                                                                           nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(32, 64, (5, 5), (1, 1), (2, 2)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                       nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 32, (1, 1)),
                                                                           nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(32, 64, (7, 7), (1, 1), (3, 3)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                       ),
                                                          LambdaReduce(lambda x, y, dim=1: torch.cat((x, y), dim),
                                                                       # Concat,
                                                                       nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 64, (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                       nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 32, (1, 1)),
                                                                           nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(32, 64, (3, 3), (1, 1), (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                       nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 32, (1, 1)),
                                                                           nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(32, 64, (5, 5), (1, 1), (2, 2)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                       nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 32, (1, 1)),
                                                                           nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(32, 64, (7, 7), (1, 1), (3, 3)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                       ),
                                                          nn.Sequential(  # Sequential,
                                                              LambdaMap(lambda x: x,  # ConcatTable,
                                                                        nn.Sequential(  # Sequential,
                                                                            LambdaReduce(
                                                                                lambda x, y, dim=1: torch.cat((x, y),
                                                                                                              dim),
                                                                                # Concat,
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 64, (1, 1)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (3, 3), (1, 1),
                                                                                              (1, 1)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (5, 5), (1, 1),
                                                                                              (2, 2)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (7, 7), (1, 1),
                                                                                              (3, 3)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                            ),
                                                                            LambdaReduce(
                                                                                lambda x, y, dim=1: torch.cat((x, y),
                                                                                                              dim),
                                                                                # Concat,
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 64, (1, 1)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (3, 3), (1, 1),
                                                                                              (1, 1)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (5, 5), (1, 1),
                                                                                              (2, 2)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (7, 7), (1, 1),
                                                                                              (3, 3)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                            ),
                                                                        ),
                                                                        nn.Sequential(  # Sequential,
                                                                            nn.AvgPool2d((2, 2), (2, 2)),
                                                                            LambdaReduce(
                                                                                lambda x, y, dim=1: torch.cat((x, y),
                                                                                                              dim),
                                                                                # Concat,
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 64, (1, 1)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (3, 3), (1, 1),
                                                                                              (1, 1)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (5, 5), (1, 1),
                                                                                              (2, 2)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (7, 7), (1, 1),
                                                                                              (3, 3)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                            ),
                                                                            LambdaReduce(
                                                                                lambda x, y, dim=1: torch.cat((x, y),
                                                                                                              dim),
                                                                                # Concat,
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 64, (1, 1)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (3, 3), (1, 1),
                                                                                              (1, 1)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (5, 5), (1, 1),
                                                                                              (2, 2)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (7, 7), (1, 1),
                                                                                              (3, 3)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                            ),
                                                                            LambdaReduce(
                                                                                lambda x, y, dim=1: torch.cat((x, y),
                                                                                                              dim),
                                                                                # Concat,
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 64, (1, 1)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (3, 3), (1, 1),
                                                                                              (1, 1)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (5, 5), (1, 1),
                                                                                              (2, 2)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                                nn.Sequential(  # Sequential,
                                                                                    nn.Conv2d(256, 32, (1, 1)),
                                                                                    nn.BatchNorm2d(32, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                    nn.Conv2d(32, 64, (7, 7), (1, 1),
                                                                                              (3, 3)),
                                                                                    nn.BatchNorm2d(64, 1e-05, 0.1,
                                                                                                   False),
                                                                                    nn.ReLU(),
                                                                                ),
                                                                            ),
                                                                            nn.UpsamplingNearest2d(scale_factor=2),
                                                                        ),
                                                                        ),
                                                              LambdaReduce(lambda x, y: x + y),  # CAddTable,
                                                          ),
                                                          LambdaReduce(lambda x, y, dim=1: torch.cat((x, y), dim),
                                                                       # Concat,
                                                                       nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 64, (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                       nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 32, (1, 1)),
                                                                           nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(32, 64, (3, 3), (1, 1), (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                       nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 32, (1, 1)),
                                                                           nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(32, 64, (5, 5), (1, 1), (2, 2)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                       nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 32, (1, 1)),
                                                                           nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(32, 64, (7, 7), (1, 1), (3, 3)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                       ),
                                                          LambdaReduce(lambda x, y, dim=1: torch.cat((x, y), dim),
                                                                       # Concat,
                                                                       nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 64, (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                       nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 64, (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(64, 64, (3, 3), (1, 1), (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                       nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 64, (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(64, 64, (7, 7), (1, 1), (3, 3)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                       nn.Sequential(  # Sequential,
                                                                           nn.Conv2d(256, 64, (1, 1)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                           nn.Conv2d(64, 64, (11, 11), (1, 1), (5, 5)),
                                                                           nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                                           nn.ReLU(),
                                                                       ),
                                                                       ),
                                                          nn.UpsamplingNearest2d(scale_factor=2),
                                                      ),
                                                      ),
                                            LambdaReduce(lambda x, y: x + y),  # CAddTable,
                                        ),
                                        LambdaReduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                                     nn.Sequential(  # Sequential,
                                                         nn.Conv2d(256, 64, (1, 1)),
                                                         nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                                     nn.Sequential(  # Sequential,
                                                         nn.Conv2d(256, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 64, (3, 3), (1, 1), (1, 1)),
                                                         nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                                     nn.Sequential(  # Sequential,
                                                         nn.Conv2d(256, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 64, (5, 5), (1, 1), (2, 2)),
                                                         nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                                     nn.Sequential(  # Sequential,
                                                         nn.Conv2d(256, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 64, (7, 7), (1, 1), (3, 3)),
                                                         nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                                     ),
                                        LambdaReduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                                     nn.Sequential(  # Sequential,
                                                         nn.Conv2d(256, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                                     nn.Sequential(  # Sequential,
                                                         nn.Conv2d(256, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 32, (3, 3), (1, 1), (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                                     nn.Sequential(  # Sequential,
                                                         nn.Conv2d(256, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 32, (5, 5), (1, 1), (2, 2)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                                     nn.Sequential(  # Sequential,
                                                         nn.Conv2d(256, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 32, (7, 7), (1, 1), (3, 3)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                                     ),
                                        nn.UpsamplingNearest2d(scale_factor=2),
                                    ),
                                    nn.Sequential(  # Sequential,
                                        LambdaReduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                                     nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                                     nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 32, (3, 3), (1, 1), (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                                     nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 32, (5, 5), (1, 1), (2, 2)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                                     nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(32, 32, (7, 7), (1, 1), (3, 3)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                                     ),
                                        LambdaReduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                                     nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 32, (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                                     nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 64, (1, 1)),
                                                         nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(64, 32, (3, 3), (1, 1), (1, 1)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                                     nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 64, (1, 1)),
                                                         nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(64, 32, (7, 7), (1, 1), (3, 3)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                                     nn.Sequential(  # Sequential,
                                                         nn.Conv2d(128, 64, (1, 1)),
                                                         nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                         nn.Conv2d(64, 32, (11, 11), (1, 1), (5, 5)),
                                                         nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                         nn.ReLU(),
                                                     ),
                                                     ),
                                    ),
                                    ),
                          LambdaReduce(lambda x, y: x + y),  # CAddTable,
                      ),
                      LambdaReduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                   nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 32, (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                                   nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 64, (1, 1)),
                                       nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(64, 32, (3, 3), (1, 1), (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                                   nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 64, (1, 1)),
                                       nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(64, 32, (5, 5), (1, 1), (2, 2)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                                   nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 64, (1, 1)),
                                       nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(64, 32, (7, 7), (1, 1), (3, 3)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                                   ),
                      LambdaReduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                   nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 16, (1, 1)),
                                       nn.BatchNorm2d(16, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                                   nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 32, (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(32, 16, (3, 3), (1, 1), (1, 1)),
                                       nn.BatchNorm2d(16, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                                   nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 32, (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(32, 16, (7, 7), (1, 1), (3, 3)),
                                       nn.BatchNorm2d(16, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                                   nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 32, (1, 1)),
                                       nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(32, 16, (11, 11), (1, 1), (5, 5)),
                                       nn.BatchNorm2d(16, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                                   ),
                      nn.UpsamplingNearest2d(scale_factor=2),
                  ),
                  nn.Sequential(  # Sequential,
                      LambdaReduce(lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                   nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 16, (1, 1)),
                                       nn.BatchNorm2d(16, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                                   nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 64, (1, 1)),
                                       nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(64, 16, (3, 3), (1, 1), (1, 1)),
                                       nn.BatchNorm2d(16, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                                   nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 64, (1, 1)),
                                       nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(64, 16, (7, 7), (1, 1), (3, 3)),
                                       nn.BatchNorm2d(16, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                                   nn.Sequential(  # Sequential,
                                       nn.Conv2d(128, 64, (1, 1)),
                                       nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                       nn.Conv2d(64, 16, (11, 11), (1, 1), (5, 5)),
                                       nn.BatchNorm2d(16, 1e-05, 0.1, False),
                                       nn.ReLU(),
                                   ),
                                   ),
                  ),
                  ),
        LambdaReduce(lambda x, y: x + y),  # CAddTable,
    ),
    nn.Conv2d(64, 1, (3, 3), (1, 1), (1, 1)),
)
